version: '3.3'

services:
  server:
    build: .
    ports:
      - '1200:22'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
