apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecology
  labels:
    category: web
    challenge: ecology
spec:
  replicas: 2
  selector:
    matchLabels:
      category: web
      challenge: ecology
  template:
    metadata:
      labels:
        category: web
        challenge: ecology
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: web
        image: gcr.io/glowing-reserve-336013/ecology
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30