apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas
  labels:
    category: web
    challenge: faas
spec:
  replicas: 2
  selector:
    matchLabels:
      category: web
      challenge: faas
  template:
    metadata:
      labels:
        category: web
        challenge: faas
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: web
        image: gcr.io/glowing-reserve-336013/faas
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30