apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle
  labels:
    category: programming
    challenge: wordle
spec:
  replicas: 2
  selector:
    matchLabels:
      category: programming
      challenge: wordle
  template:
    metadata:
      labels:
        category: programming
        challenge: wordle
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/wordle
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30