version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1700:1337'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

