apiVersion: apps/v1
kind: Deployment
metadata:
  name: man-of-steel
  labels:
    category: linux
    challenge: man-of-steel
spec:
  replicas: 2
  selector:
    matchLabels:
      category: linux
      challenge: man-of-steel
  template:
    metadata:
      labels:
        category: linux
        challenge: man-of-steel
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/man-of-steel
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 22
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30
