apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-boundaries
  labels:
    category: pwn
    challenge: my-boundaries
spec:
  replicas: 2
  selector:
    matchLabels:
      category: pwn
      challenge: my-boundaries
  template:
    metadata:
      labels:
        category: pwn
        challenge: my-boundaries
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/my-boundaries
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30